/**
 * The Virlo agent skill. Installed by `virlo skill install` into a Claude Code
 * skills directory (e.g. ./.claude/skills/virlo/SKILL.md), giving any agent in
 * that directory full context on Virlo + this CLI.
 *
 * Authored as an array of lines so markdown backticks/code fences don't collide
 * with JS template-literal syntax.
 */
export const SKILL_NAME = 'virlo';

const LINES: string[] = [
  '---',
  'name: virlo',
  'description: Short-form social intelligence via the virlo CLI (TikTok, YouTube Shorts, Instagram Reels, Meta Ads). Use when the user wants trends, viral videos, creator analysis, sound/audio research, hashtag stats, keyword or niche research, or long-term tracking of social content from the terminal.',
  '---',
  '',
  '# Virlo CLI',
  '',
  'Virlo is a short-form social intelligence platform covering TikTok, YouTube Shorts,',
  'Instagram Reels, and Meta Ads across every niche. The `virlo` command exposes the',
  'full Virlo public API from the terminal. **Reads are free; commands marked 💲 spend',
  'real money** (1 credit = $0.01).',
  '',
  'Add `--json` to any command for clean JSON on stdout (human notices and errors go to',
  'stderr), which is the right mode when you (an agent) are parsing output.',
  '',
  '## 0. Before you start — auth & money (read this first)',
  '',
  '- **Check auth:** `virlo whoami` shows the masked key + live balance. If it errors,',
  '  the user must run `virlo setup` (interactive) or set the `VIRLO_API_KEY` env var.',
  '  No key yet? Sign up at https://dev.virlo.ai, then Dashboard → API Keys → Generate Key.',
  '- **Money safety:** reads are free; 💲 commands spend real credits. 💲 commands now',
  '  REQUIRE `--yes` when run non-interactively or with `--json` — without it the CLI',
  '  refuses before making any request. `--yes` only skips the CLI\'s own prompt, though —',
  '  before running ANY 💲 command you should still check `virlo account balance` and',
  '  **confirm intent with the user first**.',
  '- **Cheapest path first:** existing results are free to re-read. Before creating new',
  '  paid work, list what already exists: `virlo orbit list`, `virlo comet list`,',
  '  `virlo tracking creators list`, `virlo tracking videos list`.',
  '- **Exit codes** (for scripting/branching): `0` ok · `2` bad input · `3` auth/config ·',
  '  `4` insufficient credits · `5` rate-limited · `6` not found · `7` network.',
  '',
  '## 1. Async model (important)',
  '',
  'Creating work (orbit, comet, satellite, tracking-collect) returns an id immediately,',
  'then runs in the background. Orbit/comet runs take ~10–45 minutes. Poll the matching',
  '`get`/`status` command, or add `--watch` (supported on orbit create/get, satellite,',
  'tracking collect) to block until the job reaches a terminal state.',
  '',
  'There are two levels of "done":',
  '',
  '- **Scrape finished** → videos/results are available. (For comet, `is_processing` is',
  '  `false`; for satellite/jobs, `status` is `completed`.)',
  '- **`finalized: true`** → the secondary AI analysis is also done and the `analysis`',
  '  field is populated. Until then `analysis` is `null`, which means "not ready yet",',
  '  NOT "no data". Re-check with the run\'s `analysis --latest` sub-command.',
  '',
  '## 2. How to read the data (interpretation rules) - unless user specifies their own',
  '',
  '- **Rank by virality, not raw views.** Score = ln(views / followers) × ln(followers).',
  '  Guide: ≥35 exceptional · 25–35 very strong · 18–25 strong · 10–18 promising.',
  '- **Never compare raw views across platforms** — medians differ hugely:',
  '  TikTok ~39K, Reels ~3.8K, Shorts ~1K. Compare within a platform, or by virality score.',
  '',
  '## 3. Intent routing — which command for the question',
  '',
  '| User asks… | Use |',
  '| --- | --- |',
  '| "What\'s working in <niche/topic>?" (one-shot) | `virlo orbit create` 💲 |',
  '| "Keep monitoring <niche>" (recurring) | `virlo comet create` 💲 |',
  '| "Tell me about this creator" | `virlo satellite creator <platform> <user> --include videos,outliers` 💲 |',
  '| "Why did this video pop / flop?" | `virlo satellite video-outlier <url> --platform <p>` 💲 |',
  '| "What about this sound / trending audio?" | `virlo sounds …` 💲 |',
  '| "Trends right now" | `virlo trends digest` (free) |',
  '| "Hashtag performance" | `virlo hashtags …` (free) |',
  '| "Track this creator/video over time" | `virlo tracking creators\\|videos add …` 💲 |',
  '',
  '## 4. Command reference (💲 = spends credits)',
  '',
  '**Setup & account**',
  '- `virlo setup` — wizard to store & validate the API key',
  '- `virlo whoami` — masked key + live balance',
  '- `virlo account balance` — credit balance',
  '',
  '**Discovery (free reads)**',
  '- `virlo hashtags list --start <YYYY-MM-DD> --end <YYYY-MM-DD> [--platform tiktok|youtube|instagram]`',
  '- `virlo hashtags performance <hashtag>`',
  '- `virlo videos digest [--platform <p>] [--limit <n>]`',
  '- `virlo trends list` · `virlo trends digest`',
  '',
  '**Orbit — keyword search (one-shot)**',
  '- `virlo orbit create --name <n> --keywords a,b --time-period today|this_week|this_month|this_year [--platforms a,b] [--min-views <n>] [--intent <text>] [--data-intelligence] [--watch]` 💲',
  '- `virlo orbit list` · `virlo orbit get <id> [--watch]`',
  '- `virlo orbit videos|slideshows|ads|outliers|sounds|trends|analysis <id>` (free sub-reads)',
  '',
  '**Comet — niche monitor (recurring)**',
  '- `virlo comet create --name <n> --keywords a,b --platforms a,b --cadence daily|weekly|monthly|cron --min-views <n> --time-range <window> [--data-intelligence]` 💲 (billed per scheduled run)',
  '- `virlo comet list [--include-inactive]` · `virlo comet get <id>` · `virlo comet update <id> …` · `virlo comet delete <id>`',
  '- `virlo comet videos|slideshows|ads|outliers|sounds|trends|analysis <id>` (free sub-reads)',
  '',
  '**Satellite — on-demand lookups**',
  '- `virlo satellite creator <platform> <username> [--include videos,outliers] [--max-videos <n>] [--watch]` 💲',
  '- `virlo satellite batch --file creators.json [--watch]` 💲 (array of {platform,username}, ≤25)',
  '- `virlo satellite video-outlier <url> --platform <p> [--watch]` 💲',
  '- `virlo satellite creator-status|batch-status|video-outlier-status <id>` (poll, free)',
  '',
  '**Sounds (all 💲)**',
  '- `virlo sounds trending` ($0.25) · `search <q>` ($0.10) · `by-creator <platform> <handle>` ($0.25)',
  '- `virlo sounds get <id>` ($0.05) · `usage-history <id>` ($0.05) · `videos <id>` ($0.25)',
  '',
  '**Tracking — long-term monitoring**',
  '- `virlo tracking creators add (--url <u>|--handle <h>) --platform <p> [--cadence <c>] [--depth standard|deep|full]` 💲 ($0.25/cycle)',
  '- `virlo tracking creators collect <id> [--depth …]` 💲 · `list|get|report|snapshots|posts|post|cadence|update|remove`',
  '- `virlo tracking videos add --url <u> --platform <p>` 💲 ($0.25/cycle) · `list|get|report|snapshots|update|remove`',
  '',
  '**Webhooks (free)**',
  '- `virlo webhooks create --url <u> --events a,b` · `list|get|update|delete|reenable|test|deliveries|retry-delivery`',
  '',
  'Run `virlo <group> --help` for every flag, with inline 💲 cost hints.',
  '',
  '## 5. Recipes',
  '',
  '```bash',
  '# Always start here (free)',
  'virlo whoami',
  'virlo account balance',
  '',
  '# Free trend/hashtag pulse',
  'virlo trends digest',
  'virlo hashtags list --start 2026-06-01 --end 2026-06-28 --platform tiktok',
  '',
  '# One-shot keyword research, wait for it (💲 — confirm with user first, then --yes',
  '# since a non-interactive/--json call requires it)',
  'virlo orbit create --name "ai tools" --keywords "ai tools,ai apps" \\',
  '  --time-period this_week --platforms tiktok,youtube --watch --yes',
  '# then read results (free)',
  'virlo orbit videos <orbit_id> --order-by views --sort desc --limit 20 --json',
  'virlo orbit analysis <orbit_id> --latest --json',
  '',
  '# Creator deep-dive (💲)',
  'virlo satellite creator tiktok @someone --include videos,outliers --watch --json --yes',
  '',
  '# Recurring niche monitor (💲 per run)',
  'virlo comet create --name "daily ai" --keywords ai --platforms tiktok \\',
  '  --cadence daily --min-views 10000 --time-range today --yes',
  '```',
  '',
  '## 6. Config & global flags',
  '',
  '- Config: `~/.virlo/config.json` (chmod 600), holds the API key. Prod endpoint is',
  '  `https://api.virlo.ai`; override only for local dev via `VIRLO_BASE_URL` or `--base-url`.',
  '- Global flags on every command: `--json`, `--api-key`, `--base-url`, `-v/--verbose`,',
  '  `--page`/`--limit` (lists), `--watch` (async jobs).',
  '- Responses are snake_case; lists paginate with `--page`/`--limit` (most max 100).',
  '- In `--json` mode, paginated responses emit one `{"pagination":{...}}` line on stderr',
  '  (check `has_next_page`/`total` there); stdout stays pure data.',
  '',
];

export const SKILL_MARKDOWN = LINES.join('\n') + '\n';
